### PR TITLE
UTH-29: Close listing when accept offer

### PR DESCRIPTION
**Pull request by momentiris**
Fixes https://linear.app/mimer-onecore/issue/UTH-29/stang-listing-vid-tacka-ja-till-erbjudande

### CODE REVIEW

**Review by driatic — COMMENTED** [review]
Curious  to know what we should do if it's not possible to close the listing (same for close offer). The only way to know is to check the logs now. Maybe `sendNotificationToRole` should be used here to notify the dev team?

**Comment by momentiris** [comment]
> Curious to know what we should do if it's not possible to close the listing (same for close offer). The only way to know is to check the logs now. Maybe `sendNotificationToRole` should be used here to notify the dev team?

Agreed we should. Will fix

**Comment by momentiris** [comment]
> Curious to know what we should do if it's not possible to close the listing (same for close offer). The only way to know is to check the logs now. Maybe `sendNotificationToRole` should be used here to notify the dev team?

Oh, we already do that further down in the process. We

> > Curious to know what we should do if it's not possible to close the listing (same for close offer). The only way to know is to check the logs now. Maybe `sendNotificationToRole` should be used here to notify the dev team?
> 
> Agreed we should. Will fix

Ac

> Curious to know what we should do if it's not possible to close the listing (same for close offer). The only way to know is to check the logs now. Maybe `sendNotificationToRole` should be used here to notify the dev team?

Actually we already send a summary to the leasing team further down in the process. Do you think we should also add sending notification to dev team?

If so, should we do rthat for each individual error (that doesnt fail the process) or could we send one in a summary like we do to the leasing team?

**Comment by momentiris** [comment]
[4e682d7](https://github.com/Bostads-AB-Mimer/onecore-core/pull/198/commits/4e682d7d8d50ab8ca71ba10f32de9f5be945da43)

@driatic

**Comment by mittistormen** [comment]
> > > Curious to know what we should do if it's not possible to close the listing (same for close offer). The only way to know is to check the logs now. Maybe `sendNotificationToRole` should be used here to notify the dev team?
> > 
> > 
> > Actually we already send a summary to the leasing team further down in the process. Do you think we should also add sending notification to dev team?
> > If so, should we do rthat for each individual error (that doesnt fail the process) or could we send one in a summary like we do to the leasing team?
> 
> A summary is probably better since there's potentially several steps in the process that can go wrong without the process exiting? Could easy be a bit spammy if there's an email for every error :) I don't know if sending the error to the leasing team is enough or if we should send an email to ourselves as well. Maybe @mittistormen can answer?

I don't understand the question? :) We probably shouldn't send to many emails. If there is an error that the leasing team can recover from or needs to know we should send them an email and if it's a critical error where the dev team need to take action we should send it the the dev team, I guess. We'll have to try it out I think

**Pull request merged**
